on: push

name: Build & Test

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Try Building
        env:
          CGO_ENABLED: 0
        run: |
          go build
      - name: Run Test
        env:
          CGO_ENABLED: 0
        run: |
          go test
