on: push

name: Integration

jobs:
  scan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Trivy and GoSec
        run: |
          sudo curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.12.0 && sudo mv bin/gosec /usr/local/bin/
      - name: Scan with Trivy
        run: |
          trivy fs --security-checks vuln,config,secret --exit-code 1 ./
      - name: Scan with GoSec
        run: |
          gosec ./...
  build:
    needs: [scan]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go_version:
          - 1.16
          - 1.17
          - 1.18
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          go build -o myproject
      - name: Run Tests
        run: |
          go test
      - name: Integration Test
        shell: bash
        run: |
          ./myproject &
          sleep 2
          res=$(curl localhost:3000)
          [[ $res == 'Hello, World!' ]]

  docker-build:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build .
