on: push

name: build

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
  compile:
    runs-on: ubuntu-latest
    steps:
      - env:
          CGO_ENABLED: 0
        run: |
          go build

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - env:
          CGO_ENABLED: 0
        run: |
          go test
