on:
  push

name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        env:
          TF_VERSION: 1.2.5
        run: |
          curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip -o terraform_${TF_VERSION}_linux_amd64.zip
          sudo mv ./terraform /usr/local/bin
      - name: Deploy Infrastructure with Terraform
        env:
          AWS_ACCESS_KEY_ID: AKIA3YWGYKDZEPKRNEWD
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          terraform init
          terraform apply -y