on:
  push:
    tags:
      - "**"
name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: saadmtsa
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_REPO: saadmtsa/devops_docker_demo_palestine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Build
        run: |
          version=${GITHUB_REF##*/}
          echo "Building Image with Version" $version
          docker build . -t $DOCKER_REPO:$version
      - name: Docker Push
        run: |
          version=${GITHUB_REF##*/}
          echo "Pushing Image with Version" $version
          docker push $DOCKER_REPO:$version
          echo "\`$DOCKER_REPO:$version\`"  > docker_link
      - name: Build Binaries
        env:
          CGO_ENABLED: 0
        run: |
          GOOS=windows GOARCH=amd64 go build -o windows_amd64
          GOOS=linux GOARCH=amd64 go build -o linux_amd64
          GOOS=darwin GOARCH=amd64 go build -o darwin_amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: docker_link
          files: |
            windows_amd64
            linux_amd64
            darwin_amd64
