on: push

name: Security

jobs:
  scan:
    name: Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install trivy
        run: |
          apt-get update
          apt-get install trivy
      - name: Scan with Trivy
        run: |
          trivy fs .
